### ISSUE TITLE
Configure to ignore 3rd party jars from git management

### ISSUE THREAD

**Issue by kazuki43zoo** [Macchinetta/spring-functionaltest#1]
I propose to add the following configuration in `.gitignore`.

```
**/3rdparty/**/*.jar
```

**Comment by tiwatsuka** [comment]
@kazuki43zoo
Thank you for your suggestion. We roughly agree with it.
We think all jar files should be ignored from git like below.
```*.jar```
Do you have another idea?

**Comment by kazuki43zoo** [comment]
`*.jar` is 👍

**Comment by tiwatsuka** [comment]
Then we'll add it on next release.

**Comment by kazuki43zoo** [comment]
👍

**Comment by macchinetta-fw** [comment]
Now we release new versions.
