### ISSUE TITLE
orderFile property is set twice.

### ISSUE THREAD

**Issue by neriudon** [Macchinetta/spring-functionaltest#2]
In spring-functionaltest-initdb project's pom.xml, code : `<orderFile>ascending</orderFile>` is written twice.
I think it is duplicate code.

https://github.com/Macchinetta/spring-functionaltest/blob/2671a07e211ceab4ccd925e21f647dfc0586a809/spring-functionaltest-initdb/pom.xml#L182-L190

**Comment by macchinetta-fw** [comment]
@neriudon 
Nice catch. We'll fix it in next version.
